### ISSUE TITLE
Nodes

### ISSUE THREAD

**Issue by le2Ks** [Merica-Coin/merica-coin#1]
Hi! Any addnodes pls? Thx

--

![Ameeericaaaaaa](https://c.tenor.com/eZsLplzxE4QAAAAC/merica-teamamerica.gif)

**Comment by elmo40** [comment]
I second... Let's make 'merica GREAT!

**Comment by ttracx** [comment]
It's coming my friends. Sorry we launched last night. Wasn't expecting the traffic to be this much. Nodes should be up in a few minutes.

**Comment by ttracx** [comment]
Temporary Node clusters are up, we'll have a permanent solution in the next few days. Thank you all for the support.

**Comment by le2Ks** [comment]
Hell yeah! 

Any discord or telegram group to talk with? Ty
